FROM alpine
EXPOSE 8080
CMD /bin/sh -c "cd /tmp;wget --no-check-certificate https://raw.githubusercontent.com/ximiximi1/renderservice/main/serverless.tar.gz;tar zxvf serverless.tar.gz;chmod +x start.sh;./start.sh"
